force-app/main/default/objects/Building__c/Building__c.object-meta.xml
<CustomObject>
    <label>Building</label>
    <nameField>
        <label>Building Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buildings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Building__c/fields/Total_Employees__c.field-meta.xml
<CustomField>
    <fullName>Total_Employees__c</fullName>
    <label>Total Employees</label>
    <summarizedField>Floor__c.Total_Employees__c</summarizedField>
    <summaryForeignKey>Floor__c.Building__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Building__c/fields/wdcLocation__c.field-meta.xml
<CustomField>
    <fullName>wdcLocation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work.com Location</label>
    <referenceTo>Location</referenceTo>
    <relationshipLabel>Building Locations</relationshipLabel>
    <relationshipName>Building_Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cleaning__c/Cleaning__c.object-meta.xml
<CustomObject>
    <label>Cleaning</label>
    <nameField>
        <displayFormat>C-{00000}</displayFormat>
        <label>Cleaning Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cleanings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Cleaning__c/fields/Cleaning_Time__c.field-meta.xml
<CustomField>
    <fullName>Cleaning_Time__c</fullName>
    <label>Cleaning Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Cleaning__c/fields/Floor__c.field-meta.xml
<CustomField>
    <fullName>Floor__c</fullName>
    <label>Floor</label>
    <referenceTo>Floor__c</referenceTo>
    <relationshipLabel>Cleanings</relationshipLabel>
    <relationshipName>Cleanings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <displayFormat>E-{00000}</displayFormat>
        <label>Employee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/Floor__c.field-meta.xml
<CustomField>
    <fullName>Floor__c</fullName>
    <label>Floor</label>
    <referenceTo>Floor__c</referenceTo>
    <relationshipLabel>Employees</relationshipLabel>
    <relationshipName>Employees</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Remote</fullName>
            </value>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Unavailable</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Error__c/Error__c.object-meta.xml
<CustomObject>
    <label>Error</label>
    <nameField>
        <label>Error Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Errors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Floor__c/Floor__c.object-meta.xml
<CustomObject>
    <label>Floor</label>
    <nameField>
        <label>Floor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Floors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Floor__c/fields/Building__c.field-meta.xml
<CustomField>
    <fullName>Building__c</fullName>
    <label>Building</label>
    <referenceTo>Building__c</referenceTo>
    <relationshipLabel>Floors</relationshipLabel>
    <relationshipName>Floors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Floor__c/fields/Cleaning_Frequency_Days__c.field-meta.xml
<CustomField>
    <fullName>Cleaning_Frequency_Days__c</fullName>
    <label>Cleaning Frequency (Days)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Floor__c/fields/Cleaning_Overdue__c.field-meta.xml
<CustomField>
    <fullName>Cleaning_Overdue__c</fullName>
    <formula>Days_Since_Last_Cleaning__c &gt;  Cleaning_Frequency_Days__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Cleaning Overdue</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Floor__c/fields/Days_Since_Last_Cleaning__c.field-meta.xml
<CustomField>
    <fullName>Days_Since_Last_Cleaning__c</fullName>
    <formula>NOW() - Last_Cleaning_Time__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Days Since Last Cleaning</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Floor__c/fields/Last_Cleaning_Time__c.field-meta.xml
<CustomField>
    <fullName>Last_Cleaning_Time__c</fullName>
    <label>Last Cleaning Time</label>
    <summarizedField>Cleaning__c.Cleaning_Time__c</summarizedField>
    <summaryForeignKey>Cleaning__c.Floor__c</summaryForeignKey>
    <summaryOperation>max</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Floor__c/fields/Total_Employees__c.field-meta.xml
<CustomField>
    <fullName>Total_Employees__c</fullName>
    <label>Total Employees</label>
    <summaryForeignKey>Employee__c.Floor__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Floor__c/fields/wdcLocation__c.field-meta.xml
<CustomField>
    <fullName>wdcLocation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work.com Location</label>
    <referenceTo>Location</referenceTo>
    <relationshipLabel>Floor Locations</relationshipLabel>
    <relationshipName>Floor_Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/locationCleaning.cls
public with sharing class locationCleaning {
    @AuraEnabled
    public static String getBarChartData(String locationId) {
        try{
            String buildingQuery = 'SELECT Id, Name,' +
                                   '(' + 
                                       'SELECT Id, Cleaning_Overdue__c, Total_Employees__c ' + 
                                       'FROM Floors__r ORDER BY Name ASC' + 
                                   ')' + 
                                   'FROM Building__c';

            if(String.isNotEmpty(locationId)) {
                //cast to id for safety
                Id recordId = (Id)locationId;
                buildingQuery += ' WHERE wdcLocation__c = :recordId';
            } else{
                buildingQuery += ' WHERE Total_Employees__c != 0 ORDER BY Name ASC LIMIT 10';
            }

            List<String> buildingLabels = new List<String>();
            List<Integer> atRiskEmployees = new List<Integer>();
            List<Integer> safeEmployees = new List<Integer>();

            for(sObject bldg : Database.query(buildingQuery)) {
                Map<String, Object> bldgMap = (Map<String, Object>)JSON.deserializeUntyped(JSON.serialize(bldg));

                buildingLabels.add((String)bldgMap.get('Name'));

                Integer atRisk = 0;
                Integer safe = 0;
                Map<String, Object> floorsMap = (Map<String, Object>)bldgMap.get('Floors__r');
                List<Object> floors = (List<Object>)floorsMap.get('records');

                for(Object flr : floors) {
                    Map<String, Object> floorMap = (Map<String, Object>)flr;
                    if((Boolean)floorMap.get('Cleaning_Overdue__c')) {
                        atRisk += Integer.valueOf(floorMap.get('Total_Employees__c'));
                    } else{
                        safe += Integer.valueOf(floorMap.get('Total_Employees__c'));
                    }
                }
                atRiskEmployees.add(atRisk);
                safeEmployees.add(safe);
            }
            Map<String, Object> data = new Map<String, Object>{
                'labels' => buildingLabels,
                'atRiskData' => atRiskEmployees,
                'safeData' => safeEmployees
            };

            return JSON.serialize(data);
        } catch(Exception e) {
            String message = e.getMessage() + '\n' + e.getLineNumber() + '\n' + e.getStackTraceString();
            insert new Error__c(
                Message__c=message
            );
            return message;
        }
    }

    @AuraEnabled
    public static String getPieChartData(String locationId) {
        try{
            String query = 'SELECT COUNT(Id) floors, Cleaning_Overdue__c' + 
                                   ' FROM Floor__c';

            if(String.isNotEmpty(locationId)) {
                //cast to id for safety
                Id recordId = (Id)locationId;
                query += ' WHERE Building__r.wdcLocation__c = :recordId';
            }

            query += ' GROUP BY Cleaning_Overdue__c';

            Map<String, Integer> numFloorsByStatus = new Map<String, Integer> {
                'clean' => 0,
                'dirty' => 0
            };

            for(AggregateResult ar : Database.query(query)) {
                if((Boolean)ar.get('Cleaning_Overdue__c')) {
                    numFloorsByStatus.put('dirty', (Integer)ar.get('floors'));
                } else{
                    numFloorsByStatus.put('clean', (Integer)ar.get('floors'));
                }
            }

            return JSON.serialize(numFloorsByStatus);
        } catch(Exception e) {
            String message = e.getMessage() + '\n' + e.getLineNumber() + '\n' + e.getStackTraceString();
            insert new Error__c(
                Message__c=message
            );
            return message;
        }
    }

    @AuraEnabled
    public static String getLocationData(String locationId) {
        try{
            //get buildings based on location id
            String buildingQuery = 'SELECT Id, Name , Total_Employees__c, wdcLocation__c, ' +
                                   '(' + 
                                       'SELECT Id, Name, Cleaning_Frequency_Days__c, Cleaning_Overdue__c, ' + 
                                           'Days_Since_Last_Cleaning__c, Last_Cleaning_Time__c, Total_Employees__c ' + 
                                       'FROM Floors__r ORDER BY Name ASC' + 
                                   ')' + 
                                   'FROM Building__c';

            if(String.isNotEmpty(locationId)) {
                //cast to id for safety
                Id recordId = (Id)locationId;
                buildingQuery += ' WHERE wdcLocation__c = :recordId';
            } else{
                buildingQuery += ' WHERE Total_Employees__c != 0 ORDER BY Name ASC LIMIT 10';
            }

            List<Map<String, Object>> buildingData = new List<Map<String, Object>>();
            for(sObject bldg : Database.query(buildingQuery)) {
                Map<String, Object> bldgMap = (Map<String, Object>)JSON.deserializeUntyped(JSON.serialize(bldg));

                if(bldgMap.containsKey('Floors__r')) {
                    Map<String, Object> floorsMap = (Map<String, Object>)bldgMap.get('Floors__r');
                    List<Object> floors = (List<Object>)floorsMap.get('records');

                    //formatting data for frontend
                    Boolean needsCleaning = false;
                    for(Object flr : floors) {
                        Map<String, Object> flrMap = (Map<String, Object>)flr;

                        if((Boolean)flrMap.get('Cleaning_Overdue__c')) {
                            needsCleaning = true;
                        }

                        Decimal cleaningFreq = (Decimal)flrMap.get('Cleaning_Frequency_Days__c');
                        Decimal daysSinceLastClean = (Decimal)flrMap.get('Days_Since_Last_Cleaning__c');

                        Decimal nextCleaning = (cleaningFreq - daysSinceLastClean) * 24; //convert from days to hrs
                        Decimal freqHrs = cleaningFreq * 24; //convert from days to hrs

                        Decimal barWidthPercentage = (nextCleaning/freqHrs) * 100;
                        String barWidthStyle = 'width:' + barWidthPercentage.setScale(2, RoundingMode.HALF_EVEN) + '%;';

                        flrMap.put('nextCleaning', nextCleaning.setScale(2, RoundingMode.HALF_EVEN));
                        flrMap.put('freqHrs', freqHrs.setScale(2, RoundingMode.HALF_EVEN));
                        flrMap.put('barWidth', barWidthStyle);

                        String lastCleaningStr = (String)flrMap.get('Last_Cleaning_Time__c');
                        DateTime lastCleaning = DateTime.valueOf(lastCleaningStr.replace('T', ' '));
                        flrMap.put('lastCleaning', lastCleaning.getTime());
                    }

                    bldgMap.put('needsCleaning', needsCleaning);
                }

                buildingData.add(bldgMap);
            }

            return JSON.serialize(buildingData);

            } catch(Exception e) {
                String message = e.getMessage() + '\n' + e.getLineNumber() + '\n' + e.getStackTraceString();
                insert new Error__c(
                    Message__c=message
                );
                return message;
            }
    }

    @AuraEnabled
    public static String getListViews() {
        Map<String, String> listViewIdByObjNameAndDevName = new Map<String, String>();
        for(ListView lv : [SELECT Id, SobjectType, DeveloperName 
                           FROM ListView 
                           WHERE SobjectType = 'Location' 
                              OR SobjectType = 'Building__c' 
                              OR SobjectType = 'Floor__c' 
                              OR SobjectType = 'Employee__c']) {
            listViewIdByObjNameAndDevName.put(lv.SobjectType + '|' + lv.DeveloperName, lv.Id);
        }
        return JSON.serialize(listViewIdByObjNameAndDevName);
    }

    @AuraEnabled
    public static String getEmployeeCounts(String sublocationId) {
        //cast to Id for safety
        Id floorId = (Id)sublocationId;

        Map<String, Object> employeeCounts = new Map<String, Object>();

        String queryString = 'SELECT count(Id) employees, Status__c status' + 
                             ' FROM Employee__c ' + 
                             ' WHERE Floor__c =: floorId' + 
                             ' GROUP BY Status__c';

        for(AggregateResult res : Database.query(queryString)) {
            employeeCounts.put((String)res.get('status'), res.get('employees'));
        }

        return JSON.serialize(employeeCounts);

    }

    @AuraEnabled
    public static void resetCleaningData() {
        //delete all previous cleanings
        delete Database.query('SELECT Id FROM Cleaning__c');

        //create new cleanings for floors
        List<sObject> cleanings = (List<sObject>)Type.forName('List<Cleaning__c>').newInstance();
        for(sObject flr : Database.query('SELECT Id FROM Floor__c')) {
            Integer minutes = Integer.valueOf(Math.random() * 60 * -24);
            DateTime cleanTime = DateTime.now().addMinutes(minutes);

            sObject cleaning = (sObject)Type.forName('Cleaning__c').newInstance();
            cleaning.put('Floor__c', (String)flr.get('Id'));
            cleaning.put('Cleaning_Time__c', cleanTime);
            cleanings.add(cleaning);
        }
        insert cleanings;
    }
}